### Lista de Exercícios de Matriz

In [1]:
import numpy as np

1. Ler uma matriz M 5 x 5, calcular e escrever as seguintes somas:
- a) da linha 3 de M
- b) da coluna 2 de M
- c) da diagonal principal
- d) da diagonal secundária
- e) de todos os elementos da matriz

In [15]:
matriz = np.array([
    [21, 3, 45, 11, 7],
    [6, 23, 12, 36, 8],
    [43, 22, 5, 76, 54],
    [3, 87, 9, 10, 20],
    [1, 38, 52, 27, 4]
])

# a) linha
line = 3
sum_line = np.sum(matriz[line - 1])
print(f'Soma da linha {line}: {sum_line}')

# b) coluna
column = 2
sum_column = np.sum(matriz[:, column - 1]) # ':' -> todas as linhas 
print(f'Soma da coluna {column}: {sum_column}')

# c) diagonal principal
# 'np.diagonal' -> função do numpy que retorna a diagonal principal de uma matriz
# 'np.fliplr' -> função do numpy que inverte a matriz da esquerda para a direita, fazendo com que a diagonal secundária
    # se torne a diagonal principal
sum_diagonal_principal = np.sum(np.diagonal(matriz))
print(f'Soma da diagonal principal: {sum_diagonal_principal}')

# d) diagonal secundária
# utilizando loop for:
sum_diagonal_secundaria = 0
qtd_lines = 5
last_index = qtd_lines - 1
for i in range(qtd_lines):
    sum_diagonal_secundaria += matriz[i, last_index - i]
print(f'Soma da diagonal secundária: {sum_diagonal_secundaria}')

# e) todos elementos
sum_all_elements = np.sum(matriz)
print(f'Soma de todos os elementos da matriz: {sum_all_elements}')

Soma da linha 3: 200
Soma da coluna 2: 173
Soma da diagonal principal: 63
Soma da diagonal secundária: 136
Soma de todos os elementos da matriz: 623


2. Ler 2 matrizes, A 4 x 6 e B 4 x 6 e criar:
- a) uma matriz S que seja a soma de A e B.
- b) uma matriz D que seja a diferença de A e B. (A – B).

    Escrever as matrizes S e D após todo cálculo estar concluído.

In [ ]:
matriz_a = np.array([
    [1, 2, 3, 4, 5, 6],
    [7, 8, 9, 10, 11, 12],
    [13, 14, 15, 16, 17, 18],
    [19, 20, 21, 22, 23, 24]
])

matriz_b = np.array([
    [2, 4, 6, 8, 10, 12],
    [14, 16, 18, 20, 22, 24],
    [26, 28, 30, 32, 34, 36],
    [38, 40, 42, 44, 46, 48]
])

matriz_s = matriz_a + matriz_b
print(f'Matriz S: \n{matriz_s}')

# usando for:
matriz_d = np.zeros((4,6))
for i in range(matriz_d.shape[0]): # acessando a linha
    for j in range(matriz_d.shape[1]): # acessando a coluna
        matriz_d[i][j] = matriz_a[i][j] - matriz_b[i][j]

print(f'Matriz D: \n{matriz_d}')

Matriz S: 
[[ 3  6  9 12 15 18]
 [21 24 27 30 33 36]
 [39 42 45 48 51 54]
 [57 60 63 66 69 72]]
Matriz D: 
[[ -1.  -2.  -3.  -4.  -5.  -6.]
 [ -7.  -8.  -9. -10. -11. -12.]
 [-13. -14. -15. -16. -17. -18.]
 [-19. -20. -21. -22. -23. -24.]]


3. Ler uma matriz A de 4 x 4, calcular e escrever as somas dos elementos marcados com o X. Utilizar estruturas de repetição.
 
    [x, x, -, -]  
    [x, x, -, -]  
    [-, -, -, -]  
    [-, -, -, -] 

    [-, -, -, -]  
    [-, -, -, -]  
    [-, -, x, x]  
    [-, -, x, x]  

    [x, -, -, -]  
    [x, x, -, -]  
    [x, x, x, -]  
    [x, x, x, x]

    [-, x, x, x]  
    [-, -, x, x]  
    [-, -, -, x]  
    [-, -, -, -]    

In [8]:
entry = input('Digite os 16 valores para uma matriz (4x4), separados por espaço: ')
values = list(map(float, entry.split()))

if len(values) != 16:
    print('Insira exatamente 16 valores para a matriz!')
else:
    matriz = np.array(values).reshape(4,4)
    sum_1 = 0
    sum_2 = 0
    sum_3 = 0
    sum_4 = 0

    print(f'Matriz: \n{matriz}')

    for i in range(2): # duas primeiras linhas
        for j in range(2): # duas primeiras colunas
            sum_1 += matriz[i,j]

    print(f'Primeira soma: {sum_1}')

    for i in range(2,4): # duas últimas linhas
        for j in range(2,4): # duas últimas colunas
            sum_2 += matriz[i,j]

    print(f'Segunda soma: {sum_2}')

    for i in range(4): # percorrendo todas as linhas
        for j in range(i + 1): # percorrendo a quantidade de colunas de acordo com i + 1 (ex: i = 0, j = 1 (apenas a primeira coluna))
            sum_3 += matriz[i,j]

    print(f'Terceira soma: {sum_3}')    

    for i in range(4): # percorrendo todas as linhas
        for j in range(i+1, 4): # percorrendo todas as colunas a partir de i+1 (ex: na coluna 0 quero os valores apartir da coluna 1) 
            sum_4 += matriz[i, j]

    print(f'Quarta soma: {sum_4}')

Matriz: 
[[59. 26. 73. 43.]
 [89. 17. 56. 85.]
 [62. 22. 61. 97.]
 [99. 49. 69. 60.]]
Primeira soma: 191.0
Segunda soma: 287.0
Terceira soma: 587.0
Quarta soma: 380.0


4. Ler uma matriz D 5 x 5 (considere que não serão informados valores duplicados). A seguir ler um número X e escreva uma mensagem indicando se o valor de X existe ou NÃO na matriz.

In [16]:
matriz = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
])

num = int(input('Informe um número: '))
exist = False

for i in range(matriz.shape[0]):
    for j in range(matriz.shape[1]):
        if num == matriz[i,j]:
            exist = True
            print(f'O valor {num} existe na matriz!')
            break

if exist == False:
    print(f'O valor {num} não existe na matriz!')

O valor 90 não existe na matriz!


5. Ler uma matriz G 5 x 5 e criar 2 vetores SL e SC de 5 elementos que contenham respectivamente as somas das linhas e das colunas de G. Escrever os vetores criados.

In [17]:
matriz = np.array([
    [2, 4, 6, 8, 10],
    [12, 14, 16, 18, 20],
    [22, 24, 26, 28, 30],
    [32, 34, 36, 38, 40],
    [42, 44, 46, 48, 50]
])

sl = []
sc = []

for i in range(matriz.shape[0]):
    sum_l = np.sum(matriz[i])
    sl.append(sum_l)
    
for j in range(matriz.shape[1]):
    sum_c = np.sum(matriz[:, j]) # acessando todas as linhas e pegando a coluna j
    sc.append(sum_c)
    
print(f'Matriz: \n{matriz}\n{"-" * 20}')
print(f'Soma das linhas: {sl}')
print(f'Soma das colunas: {sc}')

Matriz: 
[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]
 [42 44 46 48 50]]
--------------------
Soma das linhas: [30, 80, 130, 180, 230]
Soma das colunas: [110, 120, 130, 140, 150]


6. Ler uma matriz A 12 x 13 e divida todos os 13 elementos de cada uma das 12 linhas de A pelo valor do maior elemento daquela linha. Escrever a matriz A modificada.

In [31]:
matriz_a = np.random.randint(1, 100, size=(12, 13)) # gerando uma matriz de tamanho 12x13 com números aleatórios entre 1 e 100
matriz_a = matriz_a.astype(float) # convertendo todos os valores da matriz para float

print(f'Matriz Original: \n{matriz_a}\n{"-" * 20}')

for i in range(matriz_a.shape[0]):
    maior = matriz_a[i, 0]
    for j in range(1, matriz_a.shape[1]):
        if matriz_a[i,j] > maior:
            maior = matriz_a[i,j]
    
    for j in range(matriz_a.shape[1]):
        matriz_a[i,j] = matriz_a[i,j] / maior

print(f'Matriz Modificada: \n{matriz_a}')
            


Matriz Original: 
[[15.  2. 24. 54. 20. 50. 31. 61. 27. 53. 75. 76. 72.]
 [91. 62. 91. 95. 36. 61. 19. 31. 17. 25. 40. 19. 95.]
 [85. 53.  2. 49. 60. 81. 70. 78. 92. 18. 46. 41. 14.]
 [69. 49. 77. 22.  4. 45. 59.  6. 61. 28. 90. 28. 53.]
 [57. 22. 34. 36. 60. 25.  7. 19. 18.  2. 88. 17. 22.]
 [58. 56. 38. 80. 33. 17.  2.  9. 89. 17. 37. 78. 99.]
 [20. 13. 80. 62.  6. 66. 70. 37. 20. 54. 92. 61. 11.]
 [ 3. 75. 20.  3. 76. 66. 42. 11. 86. 72. 74. 62. 99.]
 [16. 75. 97. 54. 79. 64. 90. 95.  6. 26.  8. 84. 36.]
 [72. 37. 76. 33. 81. 74. 38. 35. 93. 90. 77. 15. 97.]
 [13. 97. 68. 13. 78. 29. 63.  3. 27. 90. 49. 10. 12.]
 [34. 50. 69.  2. 20. 89. 74. 78. 57. 85. 63. 30. 63.]]
--------------------
Matriz Modificada: 
[[0.19736842 0.02631579 0.31578947 0.71052632 0.26315789 0.65789474
  0.40789474 0.80263158 0.35526316 0.69736842 0.98684211 1.
  0.94736842]
 [0.95789474 0.65263158 0.95789474 1.         0.37894737 0.64210526
  0.2        0.32631579 0.17894737 0.26315789 0.42105263 0.2
  1.     

7. Ler um vetor G de 13 elementos que contenha o gabarito da loteria esportiva codificado da seguinte forma: 1-coluna um, 2-coluna do meio, 3-coluna dois.

8. Logo após, ler uma matriz 13 x 3 que contenha a aposta de um jogador. Considere que cada posição da matriz armazenará o valor 1 se for apostado, 0 caso contrário. Calcular e escrever o número de pontos obtidos pelo jogador. Escrever também o número de apostas simples, dupla ou tripla utilizadas pelo apostador.

In [6]:
g = [2, 1, 2, 3, 3, 1, 1, 2, 1, 2, 3, 1, 2]

matriz = np.array([
    [1, 0, 0],
    [1, 1, 0],
    [0, 0, 1],
    [0, 1, 0],
    [0, 0, 1],
    [1, 1, 0],
    [1, 0, 0],
    [0, 0, 1],
    [1, 0, 0],
    [0, 1, 0],
    [1, 0, 0],
    [0, 1, 0],
    [1, 1, 1]
])

pontos = 0
simples = 0
duplas = 0
triplas = 0

for i in range(len(g)):
    for j in range(3): # acessando as três colunas
        if matriz[i,j] == 1 and g[i] == (j+1):
            pontos += 1
            
for a in matriz:
    soma_a = sum(a)
    if soma_a == 1:
        simples += 1
    elif soma_a == 2:
        duplas += 1
    elif soma_a == 3:
        triplas += 1
        
print(f'\nPontos: {pontos}\nApostas simples: {simples}\nApostas duplas: {duplas}\nApostas triplas: {triplas}')


Pontos: 7
Apostas simples: 10
Apostas duplas: 2
Apostas triplas: 1
