### Lista de Exercícios Python 

In [1]:
import numpy as np

1. Crie uma matriz 2x2 e exiba seus elementos em formato de matriz.

In [2]:
matriz = np.array([
    [1,2],
    [3,4]
])

print(matriz)

[[1 2]
 [3 4]]


2. Solicite ao usuário que insira os elementos de uma matriz 3x3 e exiba a matriz formatada.

In [3]:
print('---Crie uma matriz 3x3---')
values = []
for i in range(9):
    value = int(input(f'Digite um valor para o elemento {i+1}: '))
    values.append(value)

matriz = np.array(values).reshape(3,3)

print(f'\nMatriz 3x3:\n{matriz}')

---Crie uma matriz 3x3---

Matriz 3x3:
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


3. Peça ao usuário que insira duas matrizes 2x2 e exiba a matriz resultante da soma das duas.

In [ ]:
def solicita_matriz():
    matriz = []
    for i in range(2):
        linha = []
        for j in range(2):
            value = int(input(f'Digite o valor da posição [{i+1}, {j+1}]: '))
            linha.append(value)
        matriz.append(linha)
    return np.array(matriz)

print('Informe os valores da primeira matriz: ')
matriz1 = solicita_matriz()

print('Informe os valores da segunda matriz: ')
matriz2 = solicita_matriz()

soma_matrizes = matriz1 + matriz2

print(f'\nPrimeira Matriz:\n{matriz1}\nSegunda Matriz:\n{matriz2}')
print(f'\nSoma das Matrizes:\n{soma_matrizes}')

Informe os valores da primeira matriz: 
Informe os valores da segunda matriz: 

Primeira Matriz:
[[2 4]
 [6 8]]
Segunda Matriz:
[[ 3  6]
 [ 9 12]]
Soma das Matrizes:
[[ 5 10]
 [15 20]]


4. Crie uma função que receba um número e retorne o dobro dele. 

In [1]:
def dobro(n):
    return n * 2

n = float(input('Informe um número: '))
dobro(n)

44.0

5. Crie uma função que receba um número e informe se ele é par ou ímpar.

In [ ]:
def impar_par(n):
    if n%2 == 0:
        return 'par'
    return 'ímpar'

n = float(input('Informe um número: '))
result = impar_par(n)

print(f'O valor {n} é {result}')

O valor 23.0 é ímpar


6. Crie uma função que receba uma lista de números e retorne a soma de todos  os números ímpares da lista.

In [11]:
def soma_impar(list):
    impares = []
    for i in list:
        if i%2 != 0:
            impares.append(i)
        
    soma = sum(impares)
    return soma, impares

valores = input('Informe uma lista de números separados por vírgula: ')
lista = list(map(float, valores.split(',')))

soma, impares = soma_impar(lista)
print(f'Resultado da soma de {impares}: {soma}')

Resultado da soma de [13.0, 47.0, 33.0, 77.0]: 170.0


7. Peça ao usuário para inserir um número e calcule sua raiz quadrada usando a biblioteca math. 

In [ ]:
import math 

valor = float(input('Informe um número: '))
raiz = math.sqrt(valor)

print(f'A raíz quadrada de {valor} é: {round(raiz, 3)}')

A raíz quadrada de 12.0 é: 3.464


8. Peça ao usuário para inserir uma data no formato dd/mm/aaaa e exiba o dia da semana correspondente.

In [30]:
import datetime

data_input = input('Informe uma data (dd/mm/aaaa): ')
# convertendo a string para um objeto de data
data = datetime.datetime.strptime(data_input, "%d/%m/%Y")
# função usada para obter o dia da semana correspondente a data fornecida
dia_semana = data.strftime('%A')

print(f'{data.strftime("%d/%m/%Y")}: {dia_semana}')

19/07/2006: Wednesday


9. Solicite ao usuário um número e exiba um valor aleatório entre 1 e esse número.

In [35]:
import random

n = float(input('Informe um número: '))

n_aleatorio = random.randint(1, n)

print(f'Número aleatório entre 1 e {n}: {n_aleatorio}')

Número aleatório entre 1 e 67.0: 55


10. Use o módulo random para gerar uma lista com 5 números aleatórios entre 1 e 100 e exibi-los. 

In [41]:
import random 

n_aleatorios = []
for i in range(5):
    n = random.randint(1, 100)
    n_aleatorios.append(n)

print(f'Números aleatórios: {n_aleatorios}')

Números aleatórios: [47, 15, 98, 20, 34]


11. Simule o lançamento de um dado (números de 1 a 6) e exiba o resultado após uma pausa de 2 segundos.

In [43]:
import time

print('Lançando dado...')
result = random.randint(1, 6)
time.sleep(2)

print(f'Resultado do lançamento do dado: {result}')

Lançando dado...
Resultado do lançamento do dado: 3


12. Crie um programa que crie e escreva a frase "Python é incrível!" em um arquivo chamado texto.txt. 

In [45]:
with open('texto.txt', 'w', encoding='utf-8') as file:
    file.write("Python é incrível!")

print('Arquivo registrado com sucesso!')

Arquivo registrado com sucesso!


13. Crie um programa que leia o arquivo texto.txt e exiba o conteúdo na tela. 

In [52]:
with open ('texto.txt', 'r', encoding='utf-8') as file:
    content = file.read()

print(content)

Python é incrível!


14. Peça ao usuário para inserir um nome e um telefone e armazene-os em um arquivo chamado contatos.txt. 

In [54]:
nome = input('Informe um nome: ')
tel = input('Informe o telefone: ')

with open ('contatos.txt', 'w', encoding='utf-8') as file:
    file.write(f'{nome}: {tel}')

print('Contato registrado com sucesso!')

Contato registrado com sucesso!


15. Solicite ao usuário um número e tente dividir 100 por ele, tratando o erro caso seja digitado zero.

In [66]:
try:
    n = float(input('Informe um número: '))
    result = 100 / n

    print(f'O resultado de 100/{n} é: {round(result, 2)}')
except ZeroDivisionError:
    print('Erro: Não é possível dividir por zero!')
except ValueError:
    print('Erro: Informe um número válido!')

O resultado de 100/35.0 é: 2.86


16. Peça ao usuário para inserir um número e trate possíveis erros de entrada (como digitar uma letra no lugar do número). 

In [70]:
while True:
    try:
        n = float(input('Informe um número positivo: '))

        if n <= 0:
            print('Erro: O número deve ser positivo! Tente novamente.')
            continue

        print(f'Número informado: {n}')
        break 

    except ValueError:
        print('Erro: Você não digitou um número válido!')

Erro: Você não digitou um número válido!
Erro: Você não digitou um número válido!
Número informado: 19.0


17. Solicite ao usuário um número inteiro e trate o erro caso ele tente inserir um  valor não numérico. Se a entrada for válida, exiba o quadrado do número.

In [75]:
while True:
    try:
        n = int(input("Digite um número inteiro: "))
        
        quadrado = n ** 2
        
        print(f"O quadrado de {n} é {quadrado}.")
        break
    
    except ValueError:
        print("Erro: Você não digitou um número inteiro válido! Tente novamente.")

Erro: Você não digitou um número inteiro válido! Tente novamente.
Erro: Você não digitou um número inteiro válido! Tente novamente.
O quadrado de 22 é 484.
